Uhlar/fix file extensions after airtable broke them
cesko-digital/movapp-data pull request #40
Opened 2022-11-13 22:19 UTC by JuroUhlar

2022-11-14 11:06 UTC, pionl commented
Bude potřeba ještě upravit dictionary

2022-11-14 11:06 UTC, pionl commented
alphabet vypadá, že nevytvoří žádné data navíc, dictionary pořád používá starou strukturu

2022-11-14 11:07 UTC, pionl requested changes
Bude potřeba ještě upravit dictionary

alphabet vypadá, že nevytvoří žádné data navíc, dictionary pořád používá starou strukturu

2022-11-14 11:11 UTC, JuroUhlar commented
Jj, sorry, zabudol som to označiť ako draft

2022-11-15 08:47 UTC, JuroUhlar commented
@pionl  Už by to malo byť ready :)

2022-11-15 15:09 UTC, pionl commented
zítra na to mkrnu

2022-11-16 15:58 UTC, pionl approved these changes
Za mě super, rebuild neudělal žádné změny takže super. Díky moc. Dáme squash?

2022-11-16 17:04 UTC, JuroUhlar commented
Jj, squashnime, dík za review :)

On Wed, Nov 16, 2022, 3:58 PM Martin Kluska ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Za mě super, rebuild neudělal žádné změny takže super. Díky moc. Dáme
> squash?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cesko-digital/movapp-data/pull/40#pullrequestreview-1182871740>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACV2SSL7R4GGGZRPR4WGOMDWIUABTANCNFSM6AAAAAAR7HSWZU>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-11-16 17:16 UTC, merged